[project]
name = "ukproperty-test"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.2.1",
    "jupyter>=1.1.1",
    "polars>=1.24.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
